version: 1.5
Resources:
  - testFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: test
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2
        S3Location: s3://codepipeline-us-east-1-223731750623/test_app_pipline/your-lambda-package.zip

Hooks:
  BeforeAllowTraffic:
    - location: scripts/validate_before_traffic.sh
      timeout: 300
      runas: root
  AfterAllowTraffic:
    - location: scripts/validate_after_traffic.sh
      timeout: 300
      runas: root
