version: 1.2
Resources:
  - testFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: test
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2
Hooks:
  BeforeAllowTraffic:
    - location: scripts/validate_before_traffic.sh
      timeout: 300
      runas: root
  AfterAllowTraffic:
    - location: scripts/validate_after_traffic.sh
      timeout: 300
      runas: root
